Implement RowSet and RowRange.
Unoperate/pytorch-cbt pull request #13
Opened 2021-09-09 13:02 UTC by dopiera

These classes are required to specify the rows which should be read into
pyTorch's tensors.

These classes are only a thin wrapper around the C++ classes. It needs
to be done that way because eventually, those C++ classes need to be
passed to the underlying library. An alternative approach would be to
create everything in python and create the C++ implementations when
needed but it would be more complicated for no benefit.

2021-09-10 06:05 UTC, mwalkiewicz requested changes
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/13)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[Dockerfile, line 216 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/13#-MjDB1q53eTk-vor-nIL:-MjDB1q53eTk-vor-nIM:b-ir3jkh) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/19f002ddaf6be8aac3148bfa42af6998d4250c66/Dockerfile#L216)):*
> ```Dockerfile
> # pyTorch
> RUN pip3 install \
>       nose==1.3.7 \
> ```

I wonder why are you using nose, which is unmaintained third party package, instead of `unittest` from standard lib .
___
*[plugin/setup.py, line 18 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/13#-MjDD1TnEtwwYuBt21VC:-MjDD1TnEtwwYuBt21VD:b-s47n4l) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/19f002ddaf6be8aac3148bfa42af6998d4250c66/plugin/setup.py#L18)):*
> ```Python
>       packages=['pytorch_bigtable'],
>       cmdclass={'build_ext': cpp_extension.BuildExtension},
>       test_suite='nose.collector',
> ```

If I get your intention right, you are using those parameters to be able to use `setup.py test` which is deprecated, according to a note in `test_suite` and `test_requires` description here https://setuptools.readthedocs.io/en/latest/userguide/keywords.html 
___
*[plugin/csrc/bigtable_dataset.cc, line 226 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/13#-MjDHyEv4u4s8SEKEp22:-MjDHyEwCIdhEP6o1mrc:b-8zjw8y) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/19f002ddaf6be8aac3148bfa42af6998d4250c66/plugin/csrc/bigtable_dataset.cc#L226)):*
> ```cpp
> }
> 
> std::string PrintRowRange(cbt::RowRange const& row_range) {
> ```

I can see that this file is not consistent when it comes to placement of `const` around a type. Google Style Guide recommends using `const T&`. I think that it would be wise to unify the convention while the codebase is still small (in separate PR ofc).


<!-- Sent from Reviewable.io -->

2021-09-13 09:52 UTC, kboroszko requested changes
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/13)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @dopiera and @prawilny)

___
*[plugin/pytorch_bigtable/row_set.py, line 12 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/13#-MjTXgLV59g261JJ6Viz:-MjTXgLV59g261JJ6Vj-:b-o642p9) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/19f002ddaf6be8aac3148bfa42af6998d4250c66/plugin/pytorch_bigtable/row_set.py#L12)):*
> ```Python
>         self._impl = impl
> 
>     def infinite():
> ```

a method has to either be a `staticmethod`, `classmethod` or have `self` as the first argument to be compliant with PEP8 standard.
These methods should either be module level functions or at least class methods. The use of `staticmethods` is discouraged by [Google's styleguide](https://google.github.io/styleguide/pyguide.html#2174-decision) 

We can go both ways, but maybe we don't need this wrapper class at all and can use unwrapped C++ objects?


<!-- Sent from Reviewable.io -->

2021-09-16 12:40 UTC, dopiera reviewed
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/13)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @kboroszko, @mwalkiewicz, and @prawilny)

___
*[plugin/csrc/bigtable_dataset.cc, line 226 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/13#-MjDHyEv4u4s8SEKEp22:-MjiXJ7LEtqT5zdmeJYM:b1dy1of) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/19f002ddaf6be8aac3148bfa42af6998d4250c66/plugin/csrc/bigtable_dataset.cc#L226)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I can see that this file is not consistent when it comes to placement of `const` around a type. Google Style Guide recommends using `const T&`. I think that it would be wise to unify the convention while the codebase is still small (in separate PR ofc).
</blockquote></details>

The file is, indeed, inconsistent. I will fix that in the next PR. I'd like to stick to "east const", though to remain consistent with `google-cloud-cpp` library.
___
*[plugin/pytorch_bigtable/row_set.py, line 12 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/13#-MjTXgLV59g261JJ6Viz:-MjiXXDE75Fk5o7sj7gH:b-xmbflg) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/19f002ddaf6be8aac3148bfa42af6998d4250c66/plugin/pytorch_bigtable/row_set.py#L12)):*
<details><summary><i>Previously, kboroszko wrote…</i></summary><blockquote>

a method has to either be a `staticmethod`, `classmethod` or have `self` as the first argument to be compliant with PEP8 standard.
These methods should either be module level functions or at least class methods. The use of `staticmethods` is discouraged by [Google's styleguide](https://google.github.io/styleguide/pyguide.html#2174-decision) 

We can go both ways, but maybe we don't need this wrapper class at all and can use unwrapped C++ objects?
</blockquote></details>

You fixed it yourself in the next PR :)
___
*[Dockerfile, line 216 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/13#-MjDB1q53eTk-vor-nIL:-MjiX8sN7fZcoRXTUcPA:b-dbw2pi) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/19f002ddaf6be8aac3148bfa42af6998d4250c66/Dockerfile#L216)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

I wonder why are you using nose, which is unmaintained third party package, instead of `unittest` from standard lib .
</blockquote></details>

Misleading documentation setuptools documentation. Removed.
___
*[plugin/setup.py, line 18 at r1](https://reviewable.io/reviews/unoperate/pytorch-cbt/13#-MjDD1TnEtwwYuBt21VC:-MjiXGa_9cQUPSfyVbmn:bss4a2b) ([raw file](https://github.com/unoperate/pytorch-cbt/blob/19f002ddaf6be8aac3148bfa42af6998d4250c66/plugin/setup.py#L18)):*
<details><summary><i>Previously, mwalkiewicz (Mateusz Walkiewicz) wrote…</i></summary><blockquote>

If I get your intention right, you are using those parameters to be able to use `setup.py test` which is deprecated, according to a note in `test_suite` and `test_requires` description here https://setuptools.readthedocs.io/en/latest/userguide/keywords.html 
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2021-09-16 15:16 UTC, mwalkiewicz approved these changes
> Reviewed 3 of 3 files at r2, 6 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unoperate/pytorch-cbt/13)* status: all files reviewed, 1 unresolved discussion (waiting on @kboroszko and @prawilny)



<!-- Sent from Reviewable.io -->

2021-09-16 15:17 UTC, merged